DO $$ BEGIN
    CREATE TYPE user_role AS ENUM ('USER', 'ADMIN');
    EXCEPTION WHEN duplicate_object THEN null;
END $$;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS password_hash TEXT   NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS role user_role NOT NULL DEFAULT 'USER';

ALTER TABLE users ALTER COLUMN password_hash DROP DEFAULT;